kafka:
    servers:
        bootstrap: 127.0.0.1:9092

expedia:
    credentials:
        username: EQCEVETP
        password: 123456
    imageApi:
        url: https://int.services.expediapartnercentral.com
    productApi:
        url: https://int.services.expediapartnercentral.com/products
    propertyApi:
        url: http://cheieqsctapi101
    retry:
        maxAttempts: 3
        intervalInMillis: 3000

logging:
  level:
    com.expedia: TRACE
    org.apache.kafka: WARN
    org.springframework: WARN

